const characters = {
	wu_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcxiongmu", "dczhangcai", "dcruxian"],
		clans: ["吴郡陆氏"],
	},
	dc_xujing: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcshangyu", "dccaixia"],
	},
	dc_zhaoxiang: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["refanghun", "refuhan"],
		dieAudios: ["zhaoxiang"],
	},
	dc_guansuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinzhengnan", "xiefang"],
		dieAudios: ["guansuo"],
	},
	xin_baosanniang: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["decadewuniang", "decadexushen"],
		dieAudios: ["baosanniang"],
	},
	xurong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinfu_xionghuo", "xinfu_shajue"],
	},
	dc_shixie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rebiluan", "ollixia"],
		dieAudios: ["shixie"],
	},
	dc_sp_machao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twodcspzhuiji", "twodcspshichou"],
		dieAudios: ["sp_machao"],
	},
	old_huangfusong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinfenyue"],
		names: "皇甫|嵩",
		dieAudios: ["huangfusong"],
	},
	dc_xiahouba: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rebaobian"],
		names: "夏侯|霸",
		dieAudios: ["xiahouba"],
		tempname: ["xiahouba"],
	},
	dc_daxiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcxingwu", "dcluoyan"],
		tempname: ["daxiaoqiao"],
		names: "桥|null-桥|null",
		dieAudios: ["daxiaoqiao"],
	},
	tianshangyi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcposuo", "dcxiaoren"],
	},
	sunlingluan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dclingyue", "dcpandi"],
	},
	dc_wangjun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dctongye", "dcchangqu"],
		groupBorder: "jin",
	},
	zhoubuyi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcshiji", "dcsilun"],
	},
	dc_duyu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcjianguo", "dcdyqingshi"],
		groupBorder: "jin",
	},
	ganfurenmifuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dcchanjuan", "dcxunbie"],
		names: "甘|null-糜|null",
	},
	dc_ganfuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dcshushen", "dcshenzhi"],
		names: "甘|null",
		dieAudios: ["ganfuren"],
	},
	dc_mifuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dcguixiu", "dccunsi"],
		names: "糜|null",
		dieAudios: ["mifuren"],
	},
	wanglang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["regushe", "rejici"],
	},
	ruanji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dczhaowen", "dcjiudun"],
	},
	wu_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 7,
		skills: ["dcjincui", "dcqingshi", "dczhizhe"],
		names: "诸葛|亮",
	},
	duanqiaoxiao: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dccaizhuang", "dchuayi"],
	},
	zhangjinyun: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dchuizhi", "dcjijiao"],
	},
	huanfan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcjianzheng", "dcfumou"],
	},
	chentai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcctjiuxian", "dcchenyong"],
		clans: ["颍川陈氏"],
	},
	sunyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcquanshou", "dcshexue"],
	},
	xizheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcdanyi", "dcwencan"],
	},
	dc_ruiji: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["dcwangyuan", "dclingyin", "dcliying"],
		names: "芮|null",
	},
	zerong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dccansi", "dcfozong"],
	},
	xielingyu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcyuandi", "dcxinyou"],
	},
	dc_yangbiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dczhaohan", "dcjinjie", "dcjue"],
		clans: ["弘农杨氏"],
	},
	dc_tengfanglan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcluochong", "dcaichen"],
	},
	yanghong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcjianji", "dcyuanmo"],
	},
	xuelingyun: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcxialei", "dcanzhi"],
	},
	dc_wangyun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dclianji", "dcmoucheng"],
		dieAudios: ["wangyun"],
		clans: ["太原王氏"],
	},
	dc_zhouxuān: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcwumei", "dczhanmeng"],
	},
	chengbing: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcjingzao", "dcenyu"],
	},
	dongguiren: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dclianzhi", "dclingfang", "dcfengying"],
		names: "董|null",
	},
	yuanji: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcfangdu", "dcjiexing"],
		names: "袁|null",
	},
	zhujianping: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcxiangmian", "dctianji"],
	},
	zhaozhi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dctongguan", "dcmengjie"],
	},
	dc_liuye: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcpoyuan", "dchuace"],
	},
	luyi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcyaoyi", "dcshoutan", "dcfuxue"],
	},
	dingshangwan: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcfengyan", "dcfudao"],
	},
	quanhuijie: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dchuishu", "dcyishu", "dcligong"],
	},
	dukui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcfanyin", "dcpeiqi"],
	},
	zhangfen: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcwanglu", "dcxianzhu", "dcchaixie"],
	},
	liuhui: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcgeyuan", "dcjieshu", "dcgusuan"],
	},
	dc_wangchang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dckaiji", "dcpingxi"],
		clans: ["太原王氏"],
	},
	zhaoang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		skills: ["dczhongjie", "dcsushou"],
	},
	caohua: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["caiyi", "guili"],
	},
	dc_liuyu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcsuifu", "dcpijing"],
	},
	dc_huangzu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcjinggong", "dcxiaojuan"],
	},
	laiyinger: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["xiaowu", "huaping"],
	},
	caomao: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		skills: ["qianlong", "fensi", "juetao", "zhushi"],
		isZhugong: true,
	},
	dc_luotong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["renzheng", "jinjian"],
	},
	re_fengfangnv: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["tiqi", "baoshu"],
	},
	wufan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tianyun", "wfyuyan"],
	},
	re_zhangbao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinzhoufu", "xinyingbing"],
		dieAudios: ["zhangbao"],
	},
	re_sunyi: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["syjiqiao", "syxiongyi"],
	},
	caojinyu: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["yuqi", "shanshen", "xianjing"],
	},
	zhouyi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["zhukou", "mengqing"],
	},
	re_panshu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["zhiren", "yaner"],
	},
	yangwan: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["youyan", "zhuihuan"],
	},
	ruanyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xingzuo", "miaoxian"],
	},
	fanyufeng: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["bazhan", "jiaoying"],
	},
	guozhao: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["pianchong", "zunwei"],
	},
	re_xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["rezhongjian", "recaishi"],
		dieAudios: ["xinxianying"],
	},
	liubian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["shiyuan", "dushi", "yuwei"],
		isZhugong: true,
	},
	re_liuzan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["refenyin", "liji"],
	},
	wenyang: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["xinlvli", "choujue"],
	},
	wangshuang: {
		sex: "male",
		group: "wei",
		hp: 8,
		skills: ["spzhuilie"],
	},
	huaman: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["manyi", "mansi", "souying", "zhanyuan"],
		names: "孟|null",
	},
	puyuan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["pytianjiang", "pyzhuren"],
	},
	guanlu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tuiyan", "busuan", "mingjie"],
	},
	gexuan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["gxlianhua", "zhafu"],
	},
	leitong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["kuiji"],
	},
	wulan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wlcuorui"],
	},
	lvju: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dczhengyue"],
	},
};

export default characters;
